FROM maven:3.8.8-openjdk-21-slim AS build
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:21-slim
COPY --from=build /target/chatroomapp-0.0.1-SNAPSHOT.jar chatroomapp.jar
EXPOSE 9090
ENTRYPOINT ["java", "-jar", "chatroomapp.jar"]
